version 2.1

jobs:
  build:
      docker:
        - image: python:3.10
        steps:
        - checkout
        - run:
            name: Install dependencies 
            command: pip install -r reuquirements.txt
        - run:
            name: Run tests 
            command: python testSuite.py

workflows:
  version: 2
  build:
    jobs:
      - build 
